### ISSUE TITLE
Use bloom/cuckoo filters to reduce SSTable reads

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/AugustDB#72]
# Goal

Using SSTables, it takes a long time to determine that a certain record _does not exist_.  In the case where there is neither a value nor a tombstone associated with a key, you need to read through all SSTables before you can return a negative result. 

You can use a  bloom or cuckoo filter to speed up queries for kv pairs  which don't exist.  These probabilistic data structures allow you to (mostly) determine set membership.

When the set membership test returns `false`, you can rely on the result.  The K/V pair definitely _does not exist_.

When the set membership test returns `true`, there's a possibility that it's a false positive -- it may not be in the given table.

## when to create them in memory

- on memtable flush (see the SO answer below) 
- on compaction (see https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/operations/opsTuningBloomFilters.html) 

## Background 

https://stackoverflow.com/a/39331778

https://docs.datastax.com/en/archived/cassandra/3.0/cassandra/dml/dmlAboutReads.html

## Candidate libraries

- https://github.com/gyson/blex -- [posted in elixir forum](https://elixirforum.com/t/blex-a-fast-bloom-filter-with-concurrent-accessibility-powered-by-atomics-module/19410)
- https://github.com/mpope9/exor_filter
- https://github.com/farhadi/cuckoo_filter   _most recent commits_

**Comment by Terkwood** [comment]
![Uploading Screenshot_20210807-152300.png…]()

**Comment by mpope9** [comment]
Not to resurrect the dead, but this library was recently released: https://github.com/mpope9/efuse_filter/ Binary fuse filters are smaller and faster than cuckoo and bloom and xor filters.

**Comment by Terkwood** [comment]
Thanks @mpope9! I raised #109 to track this

**Comment by mpope9** [comment]
Killer, thanks much!
